######################################################################
# 
#  File        :  $Source: /cvsroot/ijbswa/current/user.action,v $
# 
#  $Id: user.action,v 1.1 2002/04/24 02:20:24 oes Exp $
#
#  Purpose     :  User-maintained actions file, see
#                 http://www.privoxy.org/faq/questions.html#CONFIGFILES
#
######################################################################

# This is the place to add your personal exceptions and additions to
# the general policy. (Here they will be safe from updates to the
# "main" actions file, default.action.

# Say you've seen an ad on your favourite page on example.com that
# you want to get rid of. You have right-clicked the image, selected
# "copy image location" and pasted the URL below, into a { +block }
# section. Note that { +handle-as-image } need not be specified,
# since all URLs ending in .gif will be tagged as images by the
# general rules in default.action anyway:
# 
{ +block }
www.example.com/nasty-ads/sponsor.gif

# Say the site where you do your homebanking needs to open
# popup windows, but you have chosen to kill popups by
# default. This will allow it for your-example-bank.com:
#
{ -filter{popups} -kill-popups }
.your-example-bank.com

