######################################################################
# 
#  File        :  $Source: /cvsroot/ijbswa/current/standard.action,v $
# 
#  $Id: standard.action,v 1.23 2008/03/04 18:30:40 fabiankeil Exp $
#
#  Purpose     :  Provide prefedined sets of actions, see
#                 http://www.privoxy.org/user-manual/actions-file.html
#
#  Copyright   :  Written by and Copyright 2002-2007
#                 Privoxy team. http://www.privoxy.org/
#
######################################################################

######################################################################
#
# WARNING: THIS FILE IS *NOT* THE PLACE TO CUSTOMIZE YOUR CONFIGURATION!
#
#          This is not a user modifiable configuration file!
#          Local customizations and preferences should go in 
#          user.action and/or user.filter. Or use the custom editor at
#          http://p.p/. Thanks.
#
######################################################################

################
#
# Cautious settings -- safe for all sites, but offer little privacy protection
#
{ \
+hide-forwarded-for-headers \
+hide-from-header{block} \
+set-image-blocker{pattern} \
}
standard.Cautious

################
#
# Medium settings -- safe for most sites, with reasonable protection/damage tradeoff
#
{ \
+deanimate-gifs{last} \
+filter{refresh-tags} \
+filter{img-reorder} \
+filter{banners-by-size} \
+filter{webbugs} \
+filter{jumping-windows} \
+filter{ie-exploits} \
+hide-forwarded-for-headers \
+hide-from-header{block} \
+hide-referrer{conditional-block} \
+session-cookies-only \
+set-image-blocker{pattern} \
}
standard.Medium

################
#
# Advanced settings -- reasonable privacy protection but
# require some exceptions for trusted sites, most likely
# because of cookies or SSL. Also testing ground for
# new options.
#
# CAUTION: These settings can still be subverted by a
# misconfigured client that executes code from untrusted
# sources.
#
{ \
+client-header-tagger{css-requests} \
+client-header-tagger{image-requests} \
+crunch-if-none-match \
+crunch-outgoing-cookies \
+crunch-incoming-cookies \
+deanimate-gifs{last} \
+fast-redirects{check-decoded-url} \
+filter{html-annoyances} \
+filter{content-cookies} \
+filter{refresh-tags} \
+filter{img-reorder} \
+filter{banners-by-size} \
+filter{banners-by-link} \
+filter{webbugs} \
+filter{jumping-windows} \
+filter{frameset-borders} \
+filter{quicktime-kioskmode} \
+hide-if-modified-since{-60} \
+hide-forwarded-for-headers \
+hide-from-header{block} \
+hide-referrer{conditional-block} \
+limit-connect{,} \
+overwrite-last-modified{randomize} \
+set-image-blocker{pattern} \
}
standard.Advanced
